### ISSUE TITLE
Make password for the mod is not working

### ISSUE THREAD

**Issue by JoranS1** [Arczius/BrewingBards#93]
**Describe the bug**
The make a password for the mod is not working as expected
**Date Found**
The date the bug was found at (dd/mm/yyyy)
10-10-2022
**Version found**
The version the bug was found in (link to the version optional)
http://86.85.228.35/ (URL of the version where the bug was found)
**To Reproduce**
1. Go to 'Link above and login as a admin'
2. Click on 'The button that says 'Nieuwe moderator' '
3. Create 'A test moderator and give it a password'
"gebruik de aangeven notatie"
**Expected behavior**

**Actual behaviour**
A clear and concise description of what actually happens
The password give the error that the requirements for the password are not met
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10/11]
 - Browser [Vivaldi, Edge]
 - Version [Most recent]
![2022-10-12](https://user-images.githubusercontent.com/70692097/195329006-52a40246-be4e-4f02-9b30-1a7f6e696060.png)
![2022-10-12 (1)](https://user-images.githubusercontent.com/70692097/195329031-449f3cf9-25e5-4f12-aad5-00aaaaa6b843.png)

**Smartphone (please complete the following information):**
Didn't test on mobile
**Additional context**
Patterns are not good functioning

**Comment by JoranS1** [comment]
@RowinBodie made the change that the password is generated

**Comment by Arczius** [comment]
@RowinBodie can you confirm this? if you did, please assign yourself to the issue and close it with a comment stating where you made that change

**Comment by RowinBodie** [comment]
done
